
name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'      # ✅ dòng này là bắt buộc
          java-version: '17'

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew        # ✅ giúp tránh lỗi thiếu quyền

      - name: Build APK
        run: ./gradlew assembleDebug
